import { ScrollText } from "lucide-react";

import Link from "next/link";
import NavBarSheet from "@/components/nav-bar-sheet";
import NavBar from "@/components/nav-bar";
import Profile from "@/components/profile";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UrlQuery from "./url-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <div className="hidden border-r bg-muted/40 md:block">
            <div className="flex h-full max-h-screen flex-col gap-2">
              <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                <Link
                  href="/"
                  className="flex items-center gap-2 font-semibold"
                >
                  <ScrollText className="h-6 w-6" />
                  <span className="">TLDR</span>
                </Link>
              </div>
              <div className="flex-1">
                <NavBar />
              </div>
            </div>
          </div>
          <div className="flex flex-col">
            <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
              <NavBarSheet />
              <Profile />
            </header>

            <main>
              <UrlQuery />
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
